inherit_gem:
  google-style: google-style.yml

AllCops:
  Exclude:
    - "acceptance/**/*"
    - "conformance/**/*"
    - "samples/**/*"
    - "support/**/*"
    - "test/**/*"

Documentation:
  Exclude:
    - "lib/google-cloud-bigtable.rb"

Metrics/ClassLength:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - "google-cloud-bigtable.gemspec"
    - "Rakefile"
    - "lib/google-cloud-bigtable.rb"
Naming/FileName:
  Exclude:
    - "lib/google-cloud-bigtable.rb"
Style/PreferredHashMethods:
  Exclude:
    # Google::Protobuf::Map does not have key?, but uses has_key?
    - "lib/google/cloud/bigtable/column_family_map.rb"
